#!/usr/bin/env bash
# setup_chrony.sh
# Usage:
#   sudo bash setup_chrony.sh parent [ALLOW_SUBNET] [POOL]
#   sudo bash setup_chrony.sh child  <PARENT_IP>   [POOL]
#
# Examples:
#   sudo bash setup_chrony.sh parent 192.168.1.0/24
#   sudo bash setup_chrony.sh child 192.168.1.100
#
# Notes:
# - Parent mode configures this Pi as an NTP server for your LAN.
# - Child mode configures this Pi to sync from the parent Pi.
# - Works on Raspberry Pi OS / Debian-based distros.

set -euo pipefail

ROLE="${1:-}"
ARG2="${2:-}"
ARG3="${3:-}"

CHRONY_CONF="/etc/chrony/chrony.conf"
BACKUP_SUFFIX="$(date +%Y%m%d_%H%M%S)"

die() { echo "ERROR: $*" >&2; exit 1; }

need_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "Run as root: sudo bash $0 ..."
  fi
}

install_chrony() {
  echo "[*] Installing chrony (if needed)..."
  apt-get update -y
  apt-get install -y chrony
}

backup_conf() {
  if [[ -f "$CHRONY_CONF" ]]; then
    cp -a "$CHRONY_CONF" "${CHRONY_CONF}.bak_${BACKUP_SUFFIX}"
    echo "[*] Backed up ${CHRONY_CONF} -> ${CHRONY_CONF}.bak_${BACKUP_SUFFIX}"
  else
    die "Chrony config not found at $CHRONY_CONF"
  fi
}

write_parent_conf() {
  local allow_subnet="${1:-192.168.1.0/24}"
  local pool="${2:-pool pool.ntp.org iburst}"

  echo "[*] Writing PARENT (server) configuration..."
  cat > "$CHRONY_CONF" <<EOF
# Generated by setup_chrony.sh on $(date)
# Parent Pi - NTP server for LAN
# References: chrony.conf

# Upstream sources (internet). If the parent has no internet, you can comment this out.
$pool

# Allow clients on the local network
allow $allow_subnet

# If upstream is unavailable, still serve time (acts as a "local" reference)
# Stratum 8 is a common choice for a LAN master without GPS.
local stratum 8

# Step the clock quickly at boot if far off (first 3 updates)
makestep 1.0 3

# Keep the RTC in sync (useful on Pis)
rtcsync

# Helpful defaults
driftfile /var/lib/chrony/chrony.drift
logdir /var/log/chrony
EOF
}

write_child_conf() {
  local parent_ip="${1:-}"
  local pool="${2:-}"

  [[ -n "$parent_ip" ]] || die "Child mode requires parent IP. Example: sudo bash $0 child 192.168.1.100"

  echo "[*] Writing CHILD (client) configuration..."
  cat > "$CHRONY_CONF" <<EOF
# Generated by setup_chrony.sh on $(date)
# Child Pi - sync from Parent Pi

# Prefer the parent Pi as the time source
server $parent_ip iburst prefer

# Optional: keep fallback public NTP sources (uncomment if you want backup time)
# ${pool:-pool pool.ntp.org iburst}

# Step the clock quickly at boot if far off (first 3 updates)
makestep 1.0 3

# Keep the RTC in sync
rtcsync

# Helpful defaults
driftfile /var/lib/chrony/chrony.drift
logdir /var/log/chrony
EOF
}

restart_and_enable() {
  echo "[*] Enabling & restarting chrony..."
  systemctl enable chrony >/dev/null
  systemctl restart chrony
  systemctl --no-pager --full status chrony | sed -n '1,12p'
}

show_verify_cmds() {
  cat <<'EOF'

[*] Verify:
  chronyc sources -v
  chronyc tracking

[*] Firewall note:
  If you run a firewall on the parent, allow UDP/123 inbound from your LAN.

EOF
}

main() {
  need_root

  [[ -n "$ROLE" ]] || die "Missing role. Use: parent or child"

  install_chrony
  backup_conf

  case "$ROLE" in
    parent)
      ALLOW_SUBNET="${ARG2:-192.168.1.0/24}"
      POOL_LINE="${ARG3:-pool pool.ntp.org iburst}"
      write_parent_conf "$ALLOW_SUBNET" "$POOL_LINE"
      ;;
    child)
      PARENT_IP="${ARG2:-}"
      POOL_LINE="${ARG3:-pool pool.ntp.org iburst}"
      write_child_conf "$PARENT_IP" "$POOL_LINE"
      ;;
    *)
      die "Unknown role '$ROLE'. Use 'parent' or 'child'."
      ;;
  esac

  restart_and_enable
  show_verify_cmds

  echo "[+] Done."
}

main "$@"
